package com.banked.demoapp

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.widget.Button
import com.banked.checkout.CheckoutActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val button: Button = findViewById(R.id.button);

        button.setOnClickListener {
            try {
                val checkoutIntent = Intent(
                        this@MainActivity,
                        CheckoutActivity::class.java
                )

                // This should be a payment session ID generated by calling the Banked API
                // See our documentation for more details
                // https://developer.banked.com/docs/getting-started
                checkoutIntent.putExtra("paymentId", "582a9f16-e297-4258-816c-6eef814e9617")

                startActivity(checkoutIntent)
            } catch (e: ClassNotFoundException) {
                e.printStackTrace()
            }
        };

    }
}