package com.banked.demoapp

import android.content.Intent
import androidx.appcompat.app.AppCompatActivity
import android.os.Bundle
import android.util.Log
import android.widget.Button
import com.banked.checkout.CheckoutActivity

class MainActivity : AppCompatActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val appLinkIntent = intent
        val appLinkAction = appLinkIntent.action
        val appLinkData = appLinkIntent.data

        if (Intent.ACTION_VIEW == appLinkAction) {
            val id = appLinkData?.getQueryParameter("id")
            if (id != null) {
                val checkoutIntent = Intent(
                    this@MainActivity,
                    CheckoutActivity::class.java
                )

                checkoutIntent.putExtra("paymentId", id)

                startActivity(checkoutIntent)
            };
        }

        val button: Button = findViewById(R.id.button);

        button.setOnClickListener {
            val checkoutIntent = Intent(
                this@MainActivity,
                CheckoutActivity::class.java
            )

            // This should be a payment session ID generated by calling the Banked API
            // See our documentation for more details
            // https://developer.banked.com/docs/getting-started
            checkoutIntent.putExtra("paymentId", "80814403-503e-41c7-a1ee-2210d1299566")

            startActivity(checkoutIntent)
        };
    }
}